# What is a tensor?

Tensor 為 vectors、metrices 的統稱，代表一系列的數字以特定的方式排列。

Vector為 1-dimensional tensor，Metrix為 2-dimensional tensor

In [1]:
import tensorflow as tf

0-dimensional tensor (point)

In [4]:
d0 = tf.ones((1,))

1-dimensional tensor (vector)

In [5]:
d1 = tf.ones((2,))

2-dimensional tensor (matrix)

In [6]:
d2 = tf.ones((2, 2))

3-dimensional tensor

In [7]:
d3 = tf.ones((2, 2, 2))

Print the 2D, 3D tensor

In [9]:
print(d2.numpy())

[[1. 1.]
 [1. 1.]]


In [8]:
print(d3.numpy())

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


## Constants

Constants 為最簡單的一種 tensor，無法改變，無法被 trained，但可以是各種 dimensions。例如：

In [11]:
from tensorflow import constant

# 建立一個 2*3 的 constant tensor
c = constant(3, shape = [2, 3])

# 印出
print(c.numpy())

[[3 3 3]
 [3 3 3]]


例二：

In [15]:
c = constant([1, 2, 3, 4], shape = [2, 2])

print(c.numpy())

[[1 2]
 [3 4]]


### 常見的 Tensor 種類

![](Image/Image1.jpg)

In [17]:
# ones_like(t): 將輸入的 tensor t 內所有元素都改成 1 (zeros_like 則是改成 0)
one = tf.ones_like(c)

print(one.numpy())

[[1 1]
 [1 1]]


In [20]:
seven = tf.fill([3, 3], 7)
seven2 = tf.constant(7, shape = [3, 3])

print(seven.numpy())
print(seven2.numpy())

[[7 7 7]
 [7 7 7]
 [7 7 7]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]


## Variables

Variables 的數值可隨著計算而改變。然而，其 dimensions 是固定的

In [24]:
import tensorflow as tf

# define variables
a0 = tf.Variable([1, 2, 3, 4, 5, 6], dtype=tf.float32)
a1 = tf.Variable([1, 2, 3, 4, 5, 6], dtype=tf.int16)

# define a constant
b = tf.constant(2, tf.float32)

In [33]:
# 測試兩種乘法的寫法
c0 = tf.multiply(a0, b)
c1 = a0 * b

# Print the results
print(c0.numpy())
print(c1.numpy())

[ 2.  4.  6.  8. 10. 12.]
[ 2.  4.  6.  8. 10. 12.]


# Tensorflow operation

Tensorflow operation 可以利用 edge-node graph 來視覺化。例如：

![](Image/Image2.jpg)

其中，edges 代表 tensors，而 nodes 代表 operations

## 簡單的 operations

Element-wise operations: 代表 tensors 的形狀要相同，對應的 element 才能做四則運算

### 加法

Tensors中對應的元素相加 (element-wise)，所以 tensors 的形狀要相同

In [2]:
# import
from tensorflow import constant, add

# 定義兩個 0-dimensional tensors
A0 = constant([1])
B0 = constant([2])

# 定義兩個 1-dimensional tensors
A1 = constant([1, 2])
B1 = constant([3, 4])

# 定義兩個 2-dimensional tensors
A2 = constant([[1, 2], [3, 4]])
B2 = constant([[5, 6], [7, 8]])


# 加總
C0 = add(A0, B0)
C1 = add(A1, B1)
C2 = add(A2, B2)

# 印出結果
print(C0.numpy())
print(C1.numpy())
print(C2.numpy())

[3]
[4 6]
[[ 6  8]
 [10 12]]


### 乘法

有兩種乘法： element-wise 和 matrix

Element-wise multiplication: 使用 tensorflow 的 multiply() 函數， tensors 的形狀要相同 <br/>
Matrix multiplication: 使用 tensorflow 的 matmul() 函數， tensors 的 dimensions 要符合特定的關係，也就是前面的 tensor 的 column 數量要等於後面 tensor 的 row 數量 (例如矩陣相乘，必須符合 n * m 矩陣乘以 m * k 矩陣的關係)


In [11]:
# import
from tensorflow import ones, matmul, multiply

# 定義 tensors
A0 = ones(1)
A1 = ones([3, 1])
A2 = ones([3, 4])
A3 = ones([4, 3])

# 檢視形狀
print(A0.numpy())
print(A1.numpy())
print(A2.numpy())
print(A3.numpy())

print("============================= Multiply ==============================")

# multiply 運算
B00 = multiply(A0, A0)
B11 = multiply(A1, A1)
B22 = multiply(A2, A2)
B33 = multiply(A3, A3)

# results
print(B00.numpy())
print(B11.numpy())
print(B22.numpy())
print(B33.numpy())


print("============================= Matmul ==============================")

# matmul 運算
B32 = matmul(A3, A2)
B23 = matmul(A2, A3)
B31 = matmul(A3, A1)

# result
print(B32.numpy())
print(B23.numpy())
print(B31.numpy())

[1.]
[[1.]
 [1.]
 [1.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
============================= Multiply ==============================
[1.]
[[1.]
 [1.]
 [1.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
============================= Matmul ==============================
[[3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]]
[[4. 4. 4.]
 [4. 4. 4.]
 [4. 4. 4.]]
[[3.]
 [3.]
 [3.]
 [3.]]


### Reduce_sum

reduce_sum(A) 代表 sums over all dimensions of A (將 tensor A 的所有 elements 加總)

reduce_sum(A, i) 代表 sums over dimension i of A (將 tensor A 的 dimension i 的所有 elements 加總)

In [13]:
from tensorflow import ones, reduce_sum

# 定義一個 2 * 3 * 4 的 tensor
A = ones([2, 3, 4])

# reduce_sum 運算
B = reduce_sum(A)
print(B.numpy())

C1 = reduce_sum(A, 0)
C2 = reduce_sum(A, 1)
C3 = reduce_sum(A, 2)
print(C1.numpy())
print(C2.numpy())
print(C3.numpy())

24.0
[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]
[[3. 3. 3. 3.]
 [3. 3. 3. 3.]]
[[4. 4. 4.]
 [4. 4. 4.]]


# Advanced operations

包含 gradient, reshape, random 等函數

1. Tensorflow 的 gradient() 函數，會計算一個函數在某一點的斜率 <br/>
2. reshape() 函數可以將一個 tensor 轉換成其他形狀 (例如， 10 * 10 --> 100 * 1)
3. random() 函數可以產生一個存有隨機數列的 tensor

## gradient 的用處

很多機器學習或深度學習的目標是去找到一個最能描述資料的函數，因此要去 minimise 此函數與目標函數的差異，也就是找到 loss function 的最小值

這時候就要用到 gradient (斜率 slope) 來一步一步的尋找最小值 (最佳解即是找到 gradient = 0 的點，因為極值的點的微分為 0)

### 實際操作

In [5]:
# import
import tensorflow as tf

# define a variable x
x = tf.Variable(-1.0)
print(x.numpy())

# define y within instance of GradientTape
with tf.GradientTape() as tape:
    tape.watch(x)
    y = tf.multiply(x, x)

# 計算 x = -1 時 y 的 gradient
g = tape.gradient(y, x)    # 第一個參數為函數值，第二個參數為輸入值
print(g.numpy())

-1.0
-2.0


上面的 GradientTape() 可以幫助我們計算 y 對於 x 的變化率。只要在 GradientTape() 的 with statement 中定義函式 (*y = tf.multiply(x, x)*)，則 tape 中的 gradient() 函數可以直接計算函式在某一點的 gradient。例子中的斜率為 -2，代表此處的 y 會隨著 x 的上升而下降。

## reshape() 的用處

reshape() 函數對於影像處理相當有用，例如：一張 128 * 128 的灰階照片通常可由一個 128 * 128 的矩陣表示，其中，每個 element 都是介於 0 到 255 的數值。然而，大部分的機器學習演算法都只能處理向量形式的資料，因此要把這個 128 * 128 的矩陣 reshape 成一個 16384 * 1 的向量。

### 實際操作：reshape a grayscale image

![](Image/Image3.jpg)

In [9]:
# import
import tensorflow as tf

# generate a 2 * 2 grayscale image
gray = tf.random.uniform([2, 2], maxval=255, dtype="int32")
print(gray.numpy())

print("======================== reshape ========================")

# reshape the image
gray2 = tf.reshape(gray, [2*2, 1])
print(gray2.numpy())

[[149 141]
 [249  65]]
======================== reshape ========================
[[149]
 [141]
 [249]
 [ 65]]


### 實際操作2：reshape a color image (有 RGB，所以多一個 dimension)

![](Image/Image4.jpg)

In [10]:
# import 
import tensorflow as tf

# define a color image
color = tf.random.uniform([2, 2, 3], maxval=255, dtype='int32')
print(color.numpy())

print("======================== reshape ========================")

# reshape the image
color2 = tf.reshape(color, [2*2, 3])
print(color2.numpy())

[[[210  64 151]
  [210 215 139]]

 [[207 231  81]
  [162  25 171]]]
======================== reshape ========================
[[210  64 151]
 [210 215 139]
 [207 231  81]
 [162  25 171]]
